### ISSUE TITLE
Baxter resume failure

### ISSUE THREAD

**Issue by knorth55** [Affonso-Gui/roseus_resume#2]
```lisp
3.irteusgl$ (send *ri* :angle-vector (send *baxter* :init-pose) 10000)
[ INFO] [1654871557.702230315]: ;; Planned Trajectory Total Time   1.837 [sec]
[ INFO] [1654871557.702474036]: ;; Scaled Trajectory Total Time 10.000(10.000) [sec]
[ INFO] [1654871557.702516684]: ;; generated 4 points for 10.0 sec using [both_arms] group
[ INFO] [1654871557.702548955]: ;; will send to (left_s0 left_s1 left_e0 left_e1 left_w0 left_w1 left_w2 right_s0 right_s1 right_e0 right_e1 right_w0 right_w1 right_w2)
[ INFO] [1654871557.702710350]: ;; send self :angle-vector :head-controller (#<controller-action-client #X55aa2aec79e8 /robot/head/head_action>) (without planning)
[ INFO] [1654871557.708549976]: ;; send self :send-trajectory :default-controller
#<moveit_msgs::motionplanresponse #X55aa2baf34f8>
4.irteusgl$ (send *ri* :cancel-angle-vector)
t
5.irteusgl$
5.irteusgl$ (progn (send *ri* :angle-vector (send *baxter* :init-pose) 10000) (send *ri* :wait-interpolation))
[ INFO] [1654871598.780228134]: ;; Planned Trajectory Total Time   1.780 [sec]
[ INFO] [1654871598.780596319]: ;; Scaled Trajectory Total Time 10.000(10.000) [sec]
[ INFO] [1654871598.780649992]: ;; generated 4 points for 10.0 sec using [both_arms] group
[ INFO] [1654871598.780695775]: ;; will send to (left_s0 left_s1 left_e0 left_e1 left_w0 left_w1 left_w2 right_s0 right_s1 right_e0 right_e1 right_w0 right_w1 right_w2)
[ INFO] [1654871598.780978345]: ;; send self :angle-vector :head-controller (#<controller-action-client #X55aa2aec79e8 /robot/head/head_action>) (without planning)
[ INFO] [1654871598.796910661]: ;; send self :send-trajectory :default-controller
[ WARN] [1654871598.809406979]: [/robot/limb/right/follow_joint_trajectory] feedback-cb #<control_msgs::followjointtrajectoryactionfeedback #X55aa2e49eb68> received wrong goal
[ WARN] [1654871598.810442685]: [/robot/limb/left/follow_joint_trajectory] feedback-cb #<control_msgs::followjointtrajectoryactionfeedback #X55aa2e4e4d28> received wrong goal
Call Stack (max depth 20):
  0: at (while (ros::ok) (ros::ros-debug "[~A] :wait-for-result ~A ~A" ros::name-space (ros::simple-goal-states-to-string ros::simple-state) (send ros::comm-state :state)) (send self :spin-once) (if (= ros::simple-state ros::*simple-goal-state-done*) (return)) (if (> ros::timeout 0) (let* ((ros::tm (ros::time- (ros::time-now) ros::start))) (if (> (send ros::tm :to-sec) ros::timeout) (return-from :wait-for-result nil)))) (when ros::return-if-server-down (when (= (ros::get-num-publishers ros::result-topic) 0) (ros::ros-error "[~A] Unexpected returns from :wait-for-result : no publishers found for ~A" ros::name-space ros::result-topic) (return-from :wait-for-result nil)) (when (and ros::status-stamp ros::maximum-status-interval (> (send (ros::time- (ros::time-now) ros::status-stamp) :to-sec) ros::maximum-status-interval)) (ros::ros-error "[~A] Unexpected returns from :wait-for-result : status did not received for 5 seconds" ros::name-space) (return-from :wait-for-result nil))) (ros::sleep))
  1: at (let ((ros::start (ros::time-now)) (ros::result-topic (format nil "~A/result" ros::name-space))) (ros::ros-debug "[~A] :wait-for-result ~A, timeout=~A" ros::name-space (if ros::goal_id (send ros::goal_id :id)) ros::timeout) (unless ros::goal_id (ros::ros-error "[~A]
:wait-for-result (return nil when no goal exists)" ros::name-space) (return-from :wait-for-result nil)) (ros::rate ros::wait-rate) (while (ros::ok) (ros::ros-debug "[~A] :wait-for-result ~A ~A" ros::name-space (ros::simple-goal-states-to-string ros::simple-state) (send ros::comm-state :state)) (send self :spin-once) (if (= ros::simple-state ros::*simple-goal-state-done*) (return)) (if (> ros::timeout 0) (let* ((ros::tm (ros::time- (ros::time-now) ros::start))) (if (> (send ros::tm :to-sec) ros::timeout) (return-from :wait-for-result nil)))) (when ros::return-if-server-down (when (= (ros::get-num-publishers ros::result-topic) 0) (ros::ros-error "[~A] Unexpected returns from :wait-for-result : no publishers found for ~A" ros::name-space ros::result-topic) (return-from :wait-for-result nil)) (when (and ros::status-stamp ros::maximum-status-interval (> (send (ros::time- (ros::time-now) ros::status-stamp) :to-sec) ros::maximum-status-interval)) (ros::ros-error "[~A] Unexpected returns from :wait-for-result : status did not received for 5 seconds" ros::name-space) (return-from :wait-for-result nil))) (ros::sleep)) (ros::ros-debug "[~A] :wait-for-result finished ~A" ros::name-space (ros::goal-status-to-string (send self :get-state))) (if (eq (send self :get-state) actionlib_msgs::goalstatus::*preempted*) (ros::ros-warn "[~A] :wait-for-result finished with preempted status" ros::name-space)) (eq (send self :get-state) actionlib_msgs::goalstatus::*succeeded*))
  2: at (send-all controller-actions :wait-for-result :timeout timeout)
  3: at (send-all controller-actions :wait-for-result :timeout timeout)
  4: at (send-all controller-actions :wait-for-result :timeout timeout)
  5: at (cond (ctype (let ((cacts (gethash ctype controller-table))) (send-all cacts :wait-for-result :timeout timeout))) (t (send-all controller-actions :wait-for-result :timeout timeout)))
  6: at (if (send self :simulation-modep) (while (send self :interpolatingp) (send self :robot-interface-simulation-callback)) (cond (ctype (let ((cacts (gethash ctype controller-table))) (send-all cacts :wait-for-result :timeout timeout))) (t (send-all controller-actions :wait-for-result :timeout timeout))))
  7: at (send *ri* :wait-interpolation)
  8: at (progn (send *ri* :angle-vector (send *baxter* :init-pose) 10000) (send *ri* :wait-interpolation))
  9: at #<compiled-code #X55aa29908238 eustop>
NAME-ERROR: undefined function :object_recognition_msgs/objectrecognitionfeedback in (while (ros::ok) (ros::ros-debug "[~A] :wait-for-result ~A ~A" ros::name-space (ros::simple-goal-states-to-string ros::simple-state) (send ros::comm-state :state)) (send self :spin-once) (if (= ros::simple-state ros::*simple-goal-state-done*) (return)) (if (> ros::timeout 0) (let* ((ros::tm (ros::time- (ros::time-now) ros::start))) (if (> (send ros::tm :to-sec) ros::timeout) (return-from :wait-for-result nil)))) (when ros::return-if-server-down (when (= (ros::get-num-publishers ros::result-topic) 0) (ros::ros-error "[~A] Unexpected returns from :wait-for-result : no publishers found for ~A" ros::name-space ros::result-topic) (return-from :wait-for-result nil)) (when (and ros::status-stamp ros::maximum-status-interval (> (send (ros::time- (ros::time-now) ros::status-stamp) :to-sec) ros::maximum-status-interval)) (ros::ros-error "[~A] Unexpected returns from :wait-for-result : status did not received for 5 seconds" ros::name-space) (return-from :wait-for-result nil))) (ros::sleep))
```

**Comment by Affonso-Gui** [comment]
can you also attach the gdb output?
```
roseus --gdb
<run code>
```

**Comment by knorth55** [comment]
```
(gdb) bt                                                                                 
#0  0x00007fcb113e213f in __GI___select (nfds=nfds@entry=1, readfds=readfds@entry=0x55fdb400d298, writefds=writefds@entry=0x0,         
    exceptfds=exceptfds@entry=0x0, timeout=0x7ffcc857e990) at ../sysdeps/unix/sysv/linux/select.c:41
#1  0x000055fdaf92a299 in SELECT (ctx=ctx@entry=0x55fdaff4ab90, n=n@entry=4, argv=argv@entry=0x55fdaff4c280) at unixcall.c:1665
#2  0x000055fdaf954b49 in streamM3770port_selector_select (ctx=0x55fdaff4ab90, n=<optimized out>, argv=0x55fdaff4c248,                 
    env=<optimized out>) at ./stream.c:3369
#3  0x000055fdaf8f8ff7 in SEND (ctx=ctx@entry=0x55fdaff4ab90, n=n@entry=3, argv=argv@entry=0x55fdaff4c248) at leo.c:296        
#4  0x000055fdaf9a3540 in toplevelF13725reploop_select (ctx=ctx@entry=0x55fdaff4ab90, n=n@entry=2, argv=argv@entry=0x55fdaff4c1d8,
    env=<optimized out>) at ./toplevel.c:916                                   
#5  0x000055fdaf9a4fd0 in toplevelF13726reploop (ctx=0x55fdaff4ab90, n=<optimized out>, argv=<optimized out>, env=<optimized out>)
    at ./toplevel.c:1013                                                                                                               
#6  0x000055fdaf8f06dc in fcallx (ctx=0x55fdaff4ab90, n=1, argv=0x55fdaff4c180, fslot=0x55fdafc35070 <ftab+80>, sym=0x55fdb3f52e68)
    at fcall.c:43                                                                        
#7  0x000055fdaf99c88d in conditioF12621euserror (ctx=0x55fdaff4ab90, n=<optimized out>, argv=<optimized out>, env=<optimized out>)
    at ./conditions.c:1341              
#8  0x000055fdaf8f67b2 in ufuncall (ctx=ctx@entry=0x55fdaff4ab90, form=0x55fdb401f930, fn=0x55fdb4022ac8,               
    args=args@entry=0x55fdaff4c0f8, env=env@entry=0x0, noarg=noarg@entry=1) at eval.c:1611                                 
#9  0x000055fdaf909a9d in FUNCALL (ctx=ctx@entry=0x55fdaff4ab90, n=n@entry=2, argv=argv@entry=0x55fdaff4c0f0) at specials.c:130
#10 0x000055fdaf99cf4d in conditioF12618signals (ctx=0x55fdaff4ab90, n=<optimized out>, argv=0x55fdaff4c0a0, env=<optimized out>)
    at ./conditions.c:1080                                                                                                      
#11 0x000055fdaf8f67b2 in ufuncall (ctx=0x55fdaff4ab90, form=0x55fdb401f930, fn=0x55fdb401f930, args=0x55fdaff4c0a0,
    env=0x55fdb7caf108, noarg=1) at eval.c:1611                                                                   
#12 0x000055fdaf92f14e in error (ec=ec@entry=E_UNDEF) at eus.c:438            
#13 0x000055fdaf8f4b4c in getfunc (ctx=<optimized out>, f=<optimized out>) at eval.c:107                                     
#14 0x000055fdaf8f678c in ufuncall (ctx=0x55fdaff4ab90, form=0x55fdb4315f18, fn=0x55fdb4315f18, args=0x55fdaff4c090,  
    env=0x55fdb7caf108, noarg=2) at eval.c:1547
#15 0x000055fdaf92ebc5 in sigbreak () at eus.c:1111                                                                    
#16 0x000055fdaf8f657b in ufuncall (ctx=0x55fdaff4ab90, form=0x55fdb4665210, fn=0x55fdb4297530, args=0x55fdb3f9d078, env=env@entry=0x0,
    noarg=noarg@entry=-1) at eval.c:1556    
#17 0x000055fdaf8f6db6 in eval (ctx=ctx@entry=0x55fdaff4ab90, form=form@entry=0x55fdb4665210) at eval.c:1696               
#18 0x000055fdaf90aec2 in WHILE (ctx=0x55fdaff4ab90, arg=<optimized out>) at specials.c:374
#19 0x000055fdaf8f67b2 in ufuncall (ctx=0x55fdaff4ab90, form=0x55fdb4665b88, fn=0x55fdb3f89960, args=0x55fdb4665b70, env=0x0, noarg=-1)
    at eval.c:1611      
#20 0x000055fdaf8f5c74 in progn (ctx=ctx@entry=0x55fdaff4ab90, forms=0x55fdb4665e70, forms@entry=0x55fdb4665eb8) at eval.c:1733       
#21 0x000055fdaf90b299 in PARLET (ctx=0x55fdaff4ab90, args=<optimized out>) at specials.c:452
#22 0x000055fdaf8f67b2 in ufuncall (ctx=0x55fdaff4ab90, form=0x55fdb4665ee8, fn=0x55fdb3f899a8, args=0x55fdb4665ed0, env=0x0, noarg=-1)
    at eval.c:1611           
#23 0x000055fdaf8f5c74 in progn (ctx=ctx@entry=0x55fdaff4ab90, forms=forms@entry=0x55fdb4665f00) at eval.c:1733
#24 0x000055fdaf8f602e in funlambda (ctx=ctx@entry=0x55fdaff4ab90, fn=0x55fdb4663a70, formal=<optimized out>, body=0x55fdb4665f00, 
    argp=argp@entry=0x55fdaff4bfa8, env=<optimized out>, noarg=2) at eval.c:476
#25 0x000055fdaf8f8f4d in SEND (ctx=0x55fdaff4ab90, n=<optimized out>, argv=0x55fdaff4bf98) at leo.c:306
#26 0x000055fdaf8f67b2 in ufuncall (ctx=ctx@entry=0x55fdaff4ab90, form=0x55fdb5799788, fn=fn@entry=0x55fdb3f86e70, 
    args=args@entry=0x55fdaff4bf98, env=env@entry=0x0, noarg=4) at eval.c:1611
#27 0x000055fdaf9097af in APPLY (ctx=ctx@entry=0x55fdaff4ab90, n=n@entry=3, argv=argv@entry=0x55fdaff4bf80) at specials.c:104
#28 0x000055fdaf93f4f1 in commonCLO1662 (ctx=ctx@entry=0x55fdaff4ab90, n=n@entry=1, argv=argv@entry=0x55fdaff4bf68, 
    env=env@entry=0x55fdb7c6b428) at ./common.c:6321
#29 0x000055fdaf8f65f8 in ufuncall (ctx=ctx@entry=0x55fdaff4ab90, form=<optimized out>, fn=0x55fdb7c6b428, args=0x55fdaff4bf68, 
    env=env@entry=0x0, noarg=1) at eval.c:1598
#30 0x000055fdaf90a12c in MAPCAR (ctx=ctx@entry=0x55fdaff4ab90, n=n@entry=2, argv=argv@entry=0x55fdaff4bf58) at specials.c:250
#31 0x000055fdaf941f01 in commonF198send_all (ctx=0x55fdaff4ab90, n=4, argv=0x55fdaff4bf30, env=<optimized out>) at ./common.c:6305
#32 0x000055fdaf8f67b2 in ufuncall (ctx=0x55fdaff4ab90, form=0x55fdb5799788, fn=0x55fdb406d0a8, args=0x55fdb5799860, env=0x0, noarg=-1)
    at eval.c:1611
#33 0x000055fdaf8f5c74 in progn (ctx=0x55fdaff4ab90, forms=0x55fdb57997a0) at eval.c:1733
#34 0x000055fdaf8f67b2 in ufuncall (ctx=0x55fdaff4ab90, form=0x55fdb57efda8, fn=0x55fdb3f898e8, args=0x55fdb57a5200, env=0x0, noarg=-1)
    at eval.c:1611
#35 0x000055fdaf8f67b2 in ufuncall (ctx=0x55fdaff4ab90, form=0x55fdb57efe50, fn=0x55fdb3f89828, args=0x55fdb57efe38, env=0x0, noarg=-1)
    at eval.c:1611
#36 0x000055fdaf8f5c74 in progn (ctx=ctx@entry=0x55fdaff4ab90, forms=0x55fdb57efec8, forms@entry=0x55fdb57efee0) at eval.c:1733
#37 0x000055fdaf8f602e in funlambda (ctx=ctx@entry=0x55fdaff4ab90, fn=0x55fdb56f80d8, formal=<optimized out>, body=0x55fdb57efee0, 
    argp=argp@entry=0x55fdaff4beb0, env=<optimized out>, noarg=0) at eval.c:476
#38 0x000055fdaf8f8f4d in SEND (ctx=0x55fdaff4ab90, n=<optimized out>, argv=0x55fdaff4bea0) at leo.c:306
#39 0x000055fdaf8f67b2 in ufuncall (ctx=0x55fdaff4ab90, form=0x55fdb98541e8, fn=0x55fdb3f86e70, args=0x55fdb98541d0, env=0x0, noarg=-1)
    at eval.c:1611
#40 0x000055fdaf8f5c74 in progn (ctx=0x55fdaff4ab90, forms=0x55fdb9854200) at eval.c:1733
#41 0x000055fdaf8f67b2 in ufuncall (ctx=0x55fdaff4ab90, form=0x55fdb9854278, fn=0x55fdb3f8c3d8, args=0x55fdb9854260, env=0x0, 
    noarg=noarg@entry=-1) at eval.c:1611
#42 0x000055fdaf8f77c9 in eval2 (ctx=ctx@entry=0x55fdaff4ab90, form=<optimized out>, env=<optimized out>) at eval.c:1724
#43 0x000055fdaf9095b0 in EVAL (ctx=ctx@entry=0x55fdaff4ab90, n=n@entry=1, argv=argv@entry=0x55fdaff4be78) at specials.c:57
#44 0x000055fdaf9a470f in toplevelF13721rep1 (ctx=ctx@entry=0x55fdaff4ab90, n=n@entry=4, argv=argv@entry=0x55fdaff4be40, 
    env=<optimized out>) at ./toplevel.c:632
#45 0x000055fdaf9a4aaf in toplevelF13724repsel (ctx=0x55fdaff4ab90, n=<optimized out>, argv=0x55fdaff4be10, env=<optimized out>)
    at ./toplevel.c:820
#46 0x000055fdaf8f67b2 in ufuncall (ctx=ctx@entry=0x55fdaff4ab90, form=0x55fdb3ffd238, fn=fn@entry=0x55fdb40251c8, 
    args=args@entry=0x55fdaff4be10, env=env@entry=0x0, noarg=4) at eval.c:1611
#47 0x000055fdaf9097af in APPLY (ctx=ctx@entry=0x55fdaff4ab90, n=n@entry=2, argv=argv@entry=0x55fdaff4be00) at specials.c:104
#48 0x000055fdaf954bec in streamM3770port_selector_select (ctx=0x55fdaff4ab90, n=<optimized out>, argv=0x55fdaff4bdb8, 
    env=<optimized out>) at ./stream.c:3413
#49 0x000055fdaf8f8ff7 in SEND (ctx=ctx@entry=0x55fdaff4ab90, n=n@entry=3, argv=argv@entry=0x55fdaff4bdb8) at leo.c:296
#50 0x000055fdaf9a3540 in toplevelF13725reploop_select (ctx=ctx@entry=0x55fdaff4ab90, n=n@entry=2, argv=argv@entry=0x55fdaff4bd48, 
    env=<optimized out>) at ./toplevel.c:916
#51 0x000055fdaf9a4fd0 in toplevelF13726reploop (ctx=ctx@entry=0x55fdaff4ab90, n=n@entry=1, argv=argv@entry=0x55fdaff4bcf0, 
    env=<optimized out>) at ./toplevel.c:1013
#52 0x000055fdaf9a5fa2 in toplevelF13727eustop (ctx=<optimized out>, n=<optimized out>, argv=<optimized out>, env=<optimized out>)
    at ./toplevel.c:1338
#53 0x000055fdaf8f67b2 in ufuncall (ctx=0x55fdaff4ab90, form=0x55fdb3ffd238, fn=0x55fdb3ffd238, args=0x55fdaff4bc00, env=0x0, noarg=7)
    at eval.c:1611
#54 0x000055fdaf92fdd3 in toplevel (ctx=0x55fdaff4ab90, argc=7, argv=0x55fdafc37420 <mainargv>) at eus.c:1164
#55 0x000055fdaf931f93 in mainthread (ctx=0x55fdaff4ab90) at eus.c:1309
#56 0x000055fdaf8f0504 in main (argc=7, argv=<optimized out>) at eus.c:1377
```

**Comment by knorth55** [comment]
move to #3
